### ISSUE TITLE
Ask about the training time of the server used in this paper

### ISSUE THREAD

**Issue by yanlong1211** [lijfrank-open/ERNetCL#1]
Dear author
I would like to know the total training time for the models. This information is crucial for me to allocate resources appropriately and estimate the time required for my experiments. In addition, I would like to ask you to update the README file in order to better reproduce your experiment.

Thank you very much for taking the time to read my issue.l look forward to your response and hope to have the opportunity to learn more from your work.

**Comment by lijfrank** [comment]
The training time of the model is obtained by running the train_.py file.
